import java.util.Scanner;

/*
 * This Java source file was generated by the Gradle 'init' task.
 */
public class App {
public static void main(String[] args) {
    Scanner sc = new Scanner(System.in);

    
    System.out.println("이름?");
    String name = sc.nextLine();
    
    System.out.println("이메일?");
    String email = sc.nextLine();
    
    System.out.println("패스워드?");
    String password = sc.nextLine();
    
    System.out.printf("%s,%s,%s",name,email,password);
    
    sc.close();
}
}
